services:
  node_exporter:
    image: prom/node-exporter
    ports: [ "9100:9100" ]
  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_URI: "postgres:5432/postgres?sslmode=disable"
      DATA_SOURCE_USER: "postgres"
      DATA_SOURCE_PASS: "postgres"
    ports: [ "9187:9187" ]
  prometheus:
    image: prom/prometheus
    volumes:
      - ./infrastructure/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: [ "9090:9090" ]
  grafana:
    image: grafana/grafana
    ports: [ "3000:3000" ]